### PR TITLE
[access-61] dashboard

### PR DESCRIPTION
**Pull request by cjestal**
- sidebar
- company details
- user info

### CODE REVIEW

**Comment by rosoarv** [comment]
@cjestal got an error: `Trying to get property of non-object (View: home.blade.php)` after log in.

**Comment by cjestal** [comment]
@rosoarv this has something to do with no company details added to the db.

**Comment by rosoarv** [comment]
@cjestal maybe we should trapped it by displaying blank details if it doesn't exist in the db. Especially if it's newly installed, the user can't access the company details section since it'll display an error after log-in.

**Comment by cjestal** [comment]
@rosoarv please see my updates. as discussed, added logic for empty company details

**Review by rosoarv — APPROVED** [review]
looks good! please merge to master. thanks!

**Pull request merged**
